In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\admin\Desktop\HR Project\employee_attrition_dataset.csv")
df.head()

,Employee_ID,Age,Gender,Department,Job_Role,Salary,Experience (Years),Education,Work_Life_Balance,Job_Satisfaction,Attrition
0,1001,50,Male,Sales,Analyst,29077,9,Masters,1,1,No
1,1002,36,Female,Sales,Analyst,40953,13,Masters,1,5,Yes
2,1003,29,Male,Operations,Executive,96919,11,MBA,2,3,Yes
3,1004,42,Female,Operations,Associate,87889,1,MBA,4,4,No
4,1005,40,Female,HR,Manager,43821,1,Masters,1,4,Yes

In [12]:
df.describe() #statistical summary for numerical columns - mean, count, avg, etc

,Employee_ID,Age,Salary,Experience (Years),Work_Life_Balance,Job_Satisfaction
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,1200.500000,41.097500,69056.760000,6.835000,3.002500,3.067500
std,115.614301,11.187981,28400.521856,4.245331,1.406214,1.432856
min,1001.000000,22.000000,20281.000000,0.000000,1.000000,1.000000
25%,1100.750000,31.000000,46026.000000,3.000000,2.000000,2.000000
50%,1200.500000,43.000000,67514.000000,7.000000,3.000000,3.000000
75%,1300.250000,51.000000,95407.250000,11.000000,4.000000,4.000000
max,1400.000000,59.000000,119986.000000,14.000000,5.000000,5.000000

In [11]:
df.shape #number of rows and columns

(400, 11)

In [24]:
df.info() #summary of dataset and checking datatypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         400 non-null    int64
 1   Age                 400 non-null    int64
 2   Gender              400 non-null    object
 3   Department          400 non-null    object
 4   Job_Role            400 non-null    object
 5   Salary              400 non-null    int64
 6   Experience (Years)  400 non-null    int64
 7   Education           400 non-null    object
 8   Work_Life_Balance   400 non-null    int64
 9   Job_Satisfaction    400 non-null    int64
 10  Attrition           400 non-null    object
dtypes: int64(6), object(5)
memory usage: 34.5+ KB

In [9]:
df.columns #checking number of columns

Index(['Employee_ID', 'Age', 'Gender', 'Department', 'Job_Role', 'Salary',
       'Experience (Years)', 'Education', 'Work_Life_Balance',
       'Job_Satisfaction', 'Attrition'],
      dtype='object')

In [15]:
df.isnull().sum() #checking for null values

Employee_ID           0
Age                   0
Gender                0
Department            0
Job_Role              0
Salary                0
Experience (Years)    0
Education             0
Work_Life_Balance     0
Job_Satisfaction      0
Attrition             0
dtype: int64

In [17]:
df.duplicated().sum() #checking for duplicates
df.drop_duplicates(inplace=True) #drop duplicate rows if any

In [26]:
df.groupby('Gender')['Employee_ID'].count() #count of male and female employees

Gender
Female    183
Male      217
Name: Employee_ID, dtype: int64

In [29]:
df['Attrition'].value_counts() #checking if the attrition values are consistent

Attrition
No     209
Yes    191
Name: count, dtype: int64

In [34]:
df.groupby('Department')['Employee_ID'].count() #number of employees per department

Department
Finance       71
HR            78
IT            86
Operations    78
Sales         87
Name: Employee_ID, dtype: int64

In [36]:
df.groupby('Department')['Salary'].sum() #total salary per department

Department
Finance       5116427
HR            5477235
IT            5661276
Operations    5039431
Sales         6328335
Name: Salary, dtype: int64

In [46]:
def salary_group(salary): #func to group salary
    if salary <= 53000:
        return "Low"
    elif salary <= 86000:
        return "Mid"
    else:
        return "High"

df['Salary_Group'] = df['Salary'].apply(salary_group) #running the func on Salary column in dataframe
df.groupby('Salary_Group')['Employee_ID'].count().sort_values(ascending=False) #counting employees in each salary group

Salary_Group
Low     142
High    131
Mid     127
Name: Employee_ID, dtype: int64

In [59]:
def exp_group(exp): #func to create experience ranges
    if exp < 2:
        return "0-2"
    elif exp <= 5:
        return "3-5"
    elif exp <= 10:
        return "6-10"
    else:
        return "10-14"

df['Experience_Group'] = df['Experience (Years)'].apply(exp_group) #running the function on the Experience (Years) column in the dataset
df['Experience_Group'].value_counts().sort_values(ascending=False) #counting employees in each exp years range

Experience_Group
6-10     129
3-5      112
10-14    104
0-2       55
Name: count, dtype: int64

In [60]:
df.to_csv('cleaned_HR_dataset.csv', index=False)